all:
	if [ ! -e ~/.lnav/formats/custom ]; then mkdir -p ~/.lnav/formats/custom; fi
	if [ ! -e ~/.lnav/formats/custom/custom.json ]; then ln -s ~/dotfiles/lnav/formats/custom/custom.json ~/.lnav/formats/custom/custom.json; fi
