set nocompatible

let mapleader = " "
let maplocalleader = ','

call plug#begin()
Plug 'https://github.com/godlygeek/tabular.git'
Plug 'https://github.com/junegunn/fzf'
Plug 'https://github.com/majutsushi/tagbar'
Plug 'https://github.com/mattn/calendar-vim.git'
Plug 'https://github.com/scrooloose/nerdtree.git'
Plug 'https://github.com/tpope/vim-fugitive.git'
Plug 'https://github.com/tpope/vim-speeddating.git'
Plug 'https://github.com/fatih/vim-go'
Plug 'https://github.com/ycm-core/YouCompleteMe'
if has('python3')
    Plug 'git@github.com:mrxk/vim-jira.git'
endif
if v:version >=703
    Plug 'https://github.com/jceb/vim-orgmode.git', {'for': 'org'}
endif
call plug#end()

source ~/dotfiles/vim/colors.vim
source ~/dotfiles/vim/functions.vim
source ~/dotfiles/vim/keymaps.vim
source ~/dotfiles/vim/autocmds.vim
source ~/dotfiles/vim/plugins.vim
source ~/dotfiles/vim/settings.vim " must be last

